defaults:
  - _self_
  - dataset: coco
  - model: mono
  - hydra: default.yaml

# Path for saving weights, output, and logs
path:
  output_dir: 'output'
  log_dir: 'logs'

name: ???

# Hyperparameters
batch_size: 32
num_epochs: 100
learning_rate: 5e-4
scheduler:  # MultiStepLR
  milestones:
  - 60
  - 80
  gamma: 0.1

# Training configurations
image_size:
- 256
- 256

# target for training heatmap
sigma: 2  # standard deviation of the gaussian kernel
heatmap_size:  # has to be 1/4 of the input image size
- 64
- 64

gpu: 0  # GPU ID
num_workers: 8  # Number of workers for data loading
